### ISSUE TITLE
【致歉】

### ISSUE THREAD

**Issue by librarian-pku** [lib-pku/libpku#21]
1. 十分抱歉很多地方欠考虑了，现在删除了一些侵权的资料。剩下内容还将进一步确认。希望大家能引以为鉴吧（#12）。
**plz contact libpku@protonmail.com**
2. 我们最开始的出发点是想要杜绝一些拿往年题卖钱的现象。所以这本质上可能是一个往年题资料库，并不是像某些公众号所说 “GitHub上读北大"。
3. 很抱歉当年整理的时候疏忽了，给信科学术部的同学带来麻烦，被某公众号选出来的 PV 操作.pdf 是信科某位同学投稿到信科资料库的吧（我猜）。不过我挺好奇你们在 README 写个 `plz donate some money` 是什么心态，更别说一整个文件夹的盗版书了，截图的时候为什么不截全一点呢。
4. 我们低估了同学们“自发造墙”的热情。这两天接触到了一些观点，不过还是有点没想明白，为什么开个公众号卖资料就没事呢？

**Comment by lingliangyue** [comment]
同感

**Comment by Heqianxing** [comment]
感谢贡献

**Comment by zhuangzhuangzhou** [comment]
感谢贡献

**Comment by NOforgetQY** [comment]
嗯咯

**Comment by lztyt** [comment]
非常感谢，资料很有用

**Comment by leavesbnw** [comment]
你的想法很新颖，我这里也有一些资料，有些是收集而来的，有些是自己研究的，回头我整理整理。希望能帮助更多的人

**Comment by UncleAnson** [comment]
感谢

**Comment by AndrewSTree** [comment]
替我身边的朋友们感谢你们，或许对我们自身的帮助甚微，但能帮助一位需要被帮助的人，我觉得就很光彩；相比之下，那些拿人家的做公益的资料为自己牟利的人永远只能生活在阴暗里。

**Comment by TW199819** [comment]
最终还是感谢您！愿意分享资料！！！

**Comment by Ken19981102** [comment]
###
 。。。
###

**Comment by Simbazj** [comment]
来晚了，，没分享到学习资料，谁有能分享一份嘛？

**Comment by QQ3024464254** [comment]
感谢

**Comment by Mockingbirdivy** [comment]
感谢  希望有离散数学 非计科生在自学道路上到处碰壁

**Comment by Oliver10101** [comment]
谢谢学长，加油！

**Comment by lztyt** [comment]
你是？



---原始邮件---
发件人: "Oliver10101"<notifications@github.com&gt;
发送时间: 2020年2月16日(周日) 下午4:51
收件人: "lib-pku/libpku"<libpku@noreply.github.com&gt;;
抄送: "lztyt"<1484620308@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [lib-pku/libpku] 【致歉】 (#21)



谢谢学长，加油！

**Comment by Oliver10101** [comment]
学长好，我是山西财经大学16级本科在读，刚刚浏览pku小伙伴公众号文章了解到学长的github网址，遂用邮箱第一次注册了github账号并关注了学长的账号…不过还没太会用github😅
然后浏览的过程中发现了学长的致歉链接，大概了解了缘由，所以就评论了一下💫
谢谢学长建库分享资料 感激🍎
如果学长不介意的话方便添加一下学长的微信吗，关于校内资料分享的问题我也一直比较迷，想和学长讨论一下可以吗⛄️

---原始邮件---
发件人: "lztyt"<notifications@github.com&gt;
发送时间: 2020年2月16日(周日) 下午4:53
收件人: "lib-pku/libpku"<libpku@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Oliver10101"<1552647010@qq.com&gt;;
主题: Re: [lib-pku/libpku] 【致歉】 (#21)


你是？ 
 
 
 
 ---原始邮件--- 
 发件人: "Oliver10101"<notifications@github.com&amp;gt; 
 发送时间: 2020年2月16日(周日) 下午4:51 
 收件人: "lib-pku/libpku"<libpku@noreply.github.com&amp;gt;; 
 抄送: "lztyt"<1484620308@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题: Re: [lib-pku/libpku] 【致歉】 (#21) 
 
 
 
 谢谢学长，加油！

**Comment by aowind** [comment]
我为什么会收到这个？

发自我的iPhone

**Comment by Oliver10101** [comment]
抱歉，我…我也不知道这怎么弄的，我本来想发邮件给这个库的创建者，请问您是？……如果不方便的话也可以加一下这个邮箱QQ号码（我怕下次再回复可能就是别人了？）这不是垃圾邮件🤣



---原始邮件---
发件人: "Aowind"<notifications@github.com&gt;
发送时间: 2020年2月16日(周日) 晚上8:05
收件人: "lib-pku/libpku"<libpku@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Oliver10101"<1552647010@qq.com&gt;;
主题: Re: [lib-pku/libpku] 【致歉】 (#21)


我为什么会收到这个？
 
 发自我的iPhone
 
 &gt; 在 2020年2月16日，17:04，Oliver10101 <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿学长好，我是山西财经大学16级本科在读，刚刚浏览pku小伙伴公众号文章了解到学长的github网址，遂用邮箱第一次注册了github账号并关注了学长的账号…不过还没太会用github😅 
 &gt; 然后浏览的过程中发现了学长的致歉链接，大概了解了缘由，所以就评论了一下💫 
 &gt; 谢谢学长建库分享资料 感激🍎 
 &gt; 如果学长不介意的话方便添加一下学长的微信吗，关于校内资料分享的问题我也一直比较迷，想和学长讨论一下可以吗⛄️ 
 &gt; 
 &gt; ---原始邮件--- 
 &gt; 发件人: "lztyt"<notifications@github.com&amp;gt; 
 &gt; 发送时间: 2020年2月16日(周日) 下午4:53 
 &gt; 收件人: "lib-pku/libpku"<libpku@noreply.github.com&amp;gt;; 
 &gt; 抄送: "Comment"<comment@noreply.github.com&amp;gt;;"Oliver10101"<1552647010@qq.com&amp;gt;; 
 &gt; 主题: Re: [lib-pku/libpku] 【致歉】 (#21) 
 &gt; 
 &gt; 
 &gt; 你是？ 
 &gt; 
 &gt; 
 &gt; 
 &gt; ---原始邮件--- 
 &gt; 发件人: "Oliver10101"<notifications@github.com&amp;amp;gt; 
 &gt; 发送时间: 2020年2月16日(周日) 下午4:51 
 &gt; 收件人: "lib-pku/libpku"<libpku@noreply.github.com&amp;amp;gt;; 
 &gt; 抄送: "lztyt"<1484620308@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;; 
 &gt; 主题: Re: [lib-pku/libpku] 【致歉】 (#21) 
 &gt; 
 &gt; 
 &gt; 
 &gt; 谢谢学长，加油！ 
 &gt; 
 &gt; — 
 &gt; You are receiving this because you commented. 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe. 
 &gt; — 
 &gt; You are receiving this because you commented. 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; —
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Krantz-XRF** [comment]
一个issue下面所有subscribe（订阅）的人都会收到邮件消息通知，而comment一个issue会自动subscribe该issue。这就意味着如果你在某个issue下面评论过，那么你将自动设置为接收该issue的所有最新进展。

需要注意的是，GitHub的issues通常不是作为聊天区使用的，是用来反映和该repo相关的问题的，一旦问题被解决issue会被关闭，问题重现可能还会reopen。因为去年有一阵由于大量新用户涌入给好多社区造成了一些困扰，所以请新用户务必在comment之前充分考虑到“所有参与者都会收到邮件”这一点。如果希望和repo的作者单独联系，GitHub的用户信息中有邮箱地址，点击头像进入个人页面就可以看到，可以给作者单独发送邮件。

如果不希望继续收到某个issue的通知邮件，可以打开相关的GitHub issue页面（在邮件下方有链接写着“View on GitHub”），在页面右侧选择Unsubscribe；也可以直接选择邮件里的“Unsubscribe”链接。更多详情可以参考[GitHub官方帮助](https://help.github.com/cn)（页面是中文的，条目比较多，可以慢慢看）。

顺祝新春快乐，身体健康！

**Comment by aborui** [comment]
damn!what a pity.

**Comment by jiongstudeng** [comment]
您好，您的邮件已收到，我将尽快给您回复。

**Comment by huoshuyinhua699** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DaweiWangBIT** [comment]
信已收到，谢谢~~~

**Comment by Ken19981102** [comment]
okok

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月29日 19:09 |
| 收件人 | lib-pku/libpku ***@***.***> |
| 抄送人 | cui ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [lib-pku/libpku] 【致歉】 (#21) |

信已收到，谢谢~~~

**Comment by aborui** [comment]
不好意思，没想到评论会自动给你发邮件，打扰了，对不起
