### ISSUE TITLE
English please

### ISSUE THREAD

**Issue by us** [lib-pku/libpku#33]
### What is the problem with Chinese README's

Firstly, we congratulate you for getting so much star by sharing this repository with humanity.

But it is very disappointing for non-Chinese speakers when one couldn't understand what a trending repository is about.

When we see such a repo on trending, our minds are blurring like Gollum's.

![Gollum Image](https://media.giphy.com/media/V4uGHRgz0zi6Y/giphy-downsized-large.gif)

There is a way **you can help** to solve this disappointment which I believe is experienced by many people who want to know more about your valuable work and appreciate it.

### What we want:
 - Please add English translation of your README so you are sharing your work and knowledge with more people.

### How this will help you:
 - More feedback to fix and improve your project.
 - New ideas about your project.
 - Greater fame.
 - ![SungerBob Image](https://media.giphy.com/media/3o7absbD7PbTFQa0c8/source.gif)

---

_“Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something.”_

_**— Richard Stallman**_

**Thank you!**	

 > This issue created by `us/english-please` script. Please report on any error. Thank you!

**Comment by qdchenyixuan** [comment]
These docs is chinese too

**Comment by JavaAIer** [comment]
Aha, you can learn some Chinese.
Because the authors of the Github repository may not have enough time to translate them into English.

**Comment by Krantz-XRF** [comment]
It might not be very helpful to add English README only, I guess. The contents are lecture notes, slides and exam papers, almost all in Chinese. You might not be able to take advantage of these if you do not read Chinese.

**Comment by AncientTree** [comment]
Indeed English readme is in need, maybe someone related will work on it soon. it's not a big work.

If you are confused by the stars / the content of this repository / the cool east characters, 
I would say these files are examination papers and review experience for a university. Most of them are related to computer science.

As qdchenyiyuan said, the content(documents) are use Chinese too. So people can't read Chinese may not interested in these docs. Although someone with non-chinese mother language can read Chinese script, it will not be useful for most occasions. Because it is some basic knowledge learned in college.

**Comment by librarian-pku** [comment]
We don't think it makes sense to translate the README to other languages, but we are open to pull requests.

Btw, if you can't understand the README, the contents won't help you at all.
